<?php

/**
 * Hooks for production of events to an HTTP service.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 * http://www.gnu.org/copyleft/gpl.html
 *
 * @file
 * @author Eric Evans, Andrew Otto
 */

namespace MediaWiki\Extension\EventBus;

use Campaign;
use DeferredUpdates;
use ManualLogEntry;
use MediaWiki\Block\DatabaseBlock;
use MediaWiki\Deferred\LinksUpdate\LinksTable;
use MediaWiki\Deferred\LinksUpdate\LinksUpdate;
use MediaWiki\Linker\LinkTarget;
use MediaWiki\MediaWikiServices;
use MediaWiki\Page\ProperPageIdentity;
use MediaWiki\Permissions\Authority;
use MediaWiki\Revision\RevisionLookup;
use MediaWiki\Revision\RevisionRecord;
use MediaWiki\Storage\EditResult;
use MediaWiki\Title\Title;
use MediaWiki\User\UserIdentity;
use RecentChange;
use RequestContext;
use UnexpectedValueException;
use User;
use Wikimedia\Assert\Assert;
use WikiPage;

/**
 * @deprecated since EventBus 0.5.0 Use specific feature based hooks in HookHandlers/,
 * 	or even better, put them in your own extension instead of in EventBus.
 *  (e.g. Campaign hooks should move elsewhere.)
 */
class EventBusHooks {

	/**
	 * @return RevisionLookup
	 */
	private static function getRevisionLookup() {
		return MediaWikiServices::getInstance()->getRevisionLookup();
	}

	/**
	 * Creates and sends a single resource_change event to EventBus
	 *
	 * @param LinkTarget $title article title object
	 * @param array $tags the array of tags to use in the event
	 */
	private static function sendResourceChangedEvent(
		LinkTarget $title,
		array $tags
	) {
		$stream = 'resource_change';
		$eventbus = EventBus::getInstanceForStream( $stream );
		$event = $eventbus->getFactory()->createResourceChangeEvent( $stream, $title, $tags );

		DeferredUpdates::addCallableUpdate( static function () use ( $eventbus, $event ) {
			$eventbus->send( [ $event ] );
		} );
	}

	/**
	 * Occurs after the delete article request has been processed.
	 *
	 * @see https://www.mediawiki.org/wiki/Manual:Hooks/ArticleDeleteComplete
	 *
	 * @param ProperPageIdentity $page Page that was deleted.
	 * @param Authority $deleter Who deleted the page
	 * @param string $reason Reason the page was deleted
	 * @param int $pageID ID of the page that was deleted
	 * @param RevisionRecord $deletedRev Last revision of the deleted page
	 * @param ManualLogEntry $logEntry ManualLogEntry used to record the deletion
	 * @param int $archivedRevisionCount Number of revisions archived during the deletion
	 * @return true|void
	 */
	public static function onPageDeleteComplete(
		ProperPageIdentity $page,
		Authority $deleter,
		string $reason,
		int $pageID,
		RevisionRecord $deletedRev,
		ManualLogEntry $logEntry,
		int $archivedRevisionCount
	) {
		$stream = $logEntry->getType() === 'suppress' ?
			'mediawiki.page-suppress' : 'mediawiki.page-delete';
		$eventbus = EventBus::getInstanceForStream( $stream );

		$eventBusFactory = $eventbus->getFactory();
		$eventBusFactory->setCommentFormatter( MediaWikiServices::getInstance()->getCommentFormatter() );
		$title = Title::castFromPageIdentity( $page );
		Assert::postcondition( $title !== null, '$page can be cast to a LinkTarget' );
		$event = $eventBusFactory->createPageDeleteEvent(
			$stream,
			$deleter->getUser(),
			$pageID,
			$title,
			$title->isRedirect(),
			$archivedRevisionCount,
			$deletedRev,
			$reason
		);

		DeferredUpdates::addCallableUpdate(
			static function () use ( $eventbus, $event ) {
				$eventbus->send( [ $event ] );
			}
		);
	}

	/**
	 * When one or more revisions of an article are restored.
	 *
	 * @see https://www.mediawiki.org/wiki/Manual:Hooks/PageUndeleteComplete
	 *
	 * @param ProperPageIdentity $page Page that was undeleted.
	 * @param Authority $restorer Who undeleted the page
	 * @param string $reason Reason the page was undeleted
	 * @param RevisionRecord $restoredRev Last revision of the undeleted page
	 * @param ManualLogEntry $logEntry Log entry generated by the restoration
	 * @param int $restoredRevisionCount Number of revisions restored during the deletion
	 * @param bool $created Whether the undeletion result in a page being created
	 * @param array $restoredPageIds Array of all undeleted page IDs.
	 *        This will have multiple page IDs if there was more than one deleted page with the same page title.
	 * @return void This hook must not abort, it must return no value
	 */
	public static function onPageUndeleteComplete(
		ProperPageIdentity $page,
		Authority $restorer,
		string $reason,
		RevisionRecord $restoredRev,
		ManualLogEntry $logEntry,
		int $restoredRevisionCount,
		bool $created,
		array $restoredPageIds
	) {
		$stream = 'mediawiki.page-undelete';
		$eventBus = EventBus::getInstanceForStream( $stream );
		$eventBusFactory = $eventBus->getFactory();
		$eventBusFactory->setCommentFormatter( MediaWikiServices::getInstance()->getCommentFormatter() );
		$event = $eventBusFactory->createPageUndeleteEvent(
			$stream,
			$restorer->getUser(),
			// @phan-suppress-next-line PhanTypeMismatchArgumentNullable PageIdentity is not null
			Title::castFromPageIdentity( $page ),
			$reason,
			$page->getId(),
			$restoredRev,
		);

		DeferredUpdates::addCallableUpdate( static function () use ( $eventBus, $event ) {
			$eventBus->send( [ $event ] );
		} );
	}

	/**
	 * Occurs whenever a request to move an article is completed.
	 *
	 * @see https://www.mediawiki.org/wiki/Manual:Hooks/PageMoveComplete
	 *
	 * @param LinkTarget $oldTitle the old title
	 * @param LinkTarget $newTitle the new title
	 * @param UserIdentity $userIdentity User who did the move
	 * @param int $pageid database page_id of the page that's been moved
	 * @param int $redirid database page_id of the created redirect, or 0 if suppressed
	 * @param string $reason reason for the move
	 * @param RevisionRecord $newRevisionRecord revision created by the move
	 */
	public static function onPageMoveComplete(
		LinkTarget $oldTitle,
		LinkTarget $newTitle,
		UserIdentity $userIdentity,
		int $pageid,
		int $redirid,
		string $reason,
		RevisionRecord $newRevisionRecord
	) {
		$stream = 'mediawiki.page-move';
		$eventBus = EventBus::getInstanceForStream( $stream );
		$eventBusFactory = $eventBus->getFactory();
		$eventBusFactory->setCommentFormatter( MediaWikiServices::getInstance()->getCommentFormatter() );
		$event = $eventBusFactory->createPageMoveEvent(
			$stream,
			$oldTitle,
			$newTitle,
			$newRevisionRecord,
			$userIdentity,
			$reason
		);

		DeferredUpdates::addCallableUpdate(
			static function () use ( $eventBus, $event ) {
				$eventBus->send( [ $event ] );
			}
		);
	}

	/**
	 * Called when changing visibility of one or more revisions of an article.
	 *
	 * @see https://www.mediawiki.org/wiki/Manual:Hooks/ArticleRevisionVisibilitySet
	 *
	 * @param Title $title title object of the article
	 * @param array $revIds array of integer revision IDs
	 * @param array $visibilityChangeMap map of revision id to oldBits and newBits.
	 *              This array can be examined to determine exactly what visibility
	 *              bits have changed for each revision.  This array is of the form
	 *              [id => ['oldBits' => $oldBits, 'newBits' => $newBits], ... ]
	 */
	public static function onArticleRevisionVisibilitySet(
		Title $title,
		array $revIds,
		array $visibilityChangeMap
	) {
		$stream = 'mediawiki.revision-visibility-change';
		$events = [];
		$eventBus = EventBus::getInstanceForStream( $stream );
		$performer = RequestContext::getMain()->getUser();
		$performer->loadFromId();

		// Create a  event
		// for each revId that was changed.
		foreach ( $revIds as $revId ) {
			// Read from primary since due to replication lag the updated field visibility
			// might still not be available on a replica and we are at risk of leaking
			// just suppressed data.
			$revision = self::getRevisionLookup()
				->getRevisionById( $revId, RevisionLookup::READ_LATEST );

			// If the page is deleted simultaneously (null $revision) or if
			// this revId is not in the $visibilityChangeMap, then we can't
			// send a meaningful event.
			if ( $revision === null ) {
				wfDebug(
					__METHOD__ . ' revision ' . $revId .
					' could not be found and may have been deleted. Cannot ' .
					"create mediawiki/revision/visibility-change event.\n"
				);
				continue;
			} elseif ( !array_key_exists( $revId, $visibilityChangeMap ) ) {
				// This should not happen, log it.
				wfDebug(
					__METHOD__ . ' revision id ' . $revId .
					' not found in visibilityChangeMap. Cannot create ' .
					"mediawiki/revision/visibility-change event.\n"
				);
				continue;
			} else {
				$eventBusFactory = $eventBus->getFactory();
				$eventBusFactory->setCommentFormatter( MediaWikiServices::getInstance()->getCommentFormatter() );
				$events[] = $eventBusFactory->createRevisionVisibilityChangeEvent(
					$stream,
					$revision,
					$performer,
					$visibilityChangeMap[$revId]
				);
			}
		}

		if ( $events === [] ) {
			// For revision-visibility-set it's possible that
			// the page was deleted simultaneously and we can not
			// send a meaningful event.
			return;
		}

		DeferredUpdates::addCallableUpdate(
			static function () use ( $eventBus, $events ) {
				$eventBus->send( $events );
			}
		);
	}

	/**
	 * Callback for article purge.
	 *
	 * @see https://www.mediawiki.org/wiki/Manual:Hooks/ArticlePurge
	 *
	 * @param WikiPage $wikiPage
	 */
	public static function onArticlePurge( WikiPage $wikiPage ) {
		self::sendResourceChangedEvent( $wikiPage->getTitle(), [ 'purge' ] );
	}

	/**
	 * Occurs after the save page request has been processed.
	 *
	 * Sends an event if the new revision was also a page creation
	 *
	 * @see https://www.mediawiki.org/wiki/Manual:Hooks/PageSaveComplete
	 *
	 * @param WikiPage $wikiPage
	 * @param UserIdentity $userIdentity
	 * @param string $summary
	 * @param int $flags
	 * @param RevisionRecord $revisionRecord
	 * @param EditResult $editResult
	 */
	public static function onPageSaveComplete(
		WikiPage $wikiPage,
		UserIdentity $userIdentity,
		string $summary,
		int $flags,
		RevisionRecord $revisionRecord,
		EditResult $editResult
	) {
		if ( $editResult->isNullEdit() ) {
			self::sendResourceChangedEvent( $wikiPage->getTitle(), [ 'null_edit' ] );
			return;
		}

		if ( $flags & EDIT_NEW ) {
			// Not just a new revision, but a new page
			self::sendRevisionCreateEvent(
				'mediawiki.page-create',
				$revisionRecord
			);
		}
	}

	/**
	 * Occurs after a revision is inserted into the database.
	 *
	 * @see https://www.mediawiki.org/wiki/Manual:Hooks/RevisionRecordInserted
	 *
	 * @param RevisionRecord $revisionRecord RevisionRecord that has just been inserted
	 */
	public static function onRevisionRecordInserted( RevisionRecord $revisionRecord ) {
		self::sendRevisionCreateEvent(
			'mediawiki.revision-create',
			$revisionRecord
		);
	}

	/**
	 * @param string $stream
	 * @param RevisionRecord $revisionRecord
	 */
	private static function sendRevisionCreateEvent(
		string $stream,
		RevisionRecord $revisionRecord
	) {
		$eventBus = EventBus::getInstanceForStream( $stream );
		$eventBusFactory = $eventBus->getFactory();
		$eventBusFactory->setCommentFormatter(
			MediaWikiServices::getInstance()->getCommentFormatter()
		);
		$event = $eventBusFactory->createRevisionCreateEvent(
			$stream,
			$revisionRecord
		);

		DeferredUpdates::addCallableUpdate(
			static function () use ( $eventBus, $event ) {
				$eventBus->send( [ $event ] );
			}
		);
	}

	/**
	 * Occurs after the request to block an IP or user has been processed
	 *
	 * @see https://www.mediawiki.org/wiki/Manual:Hooks/BlockIpComplete
	 *
	 * @param DatabaseBlock $block the block object that was saved
	 * @param User $user the user who did the block (not the one being blocked)
	 * @param DatabaseBlock|null $previousBlock the previous block state for the block target.
	 *        null if this is a new block target.
	 */
	public static function onBlockIpComplete(
		DatabaseBlock $block,
		User $user,
		?DatabaseBlock $previousBlock
	) {
		$stream = 'mediawiki.user-blocks-change';
		$eventBus = EventBus::getInstanceForStream( 'mediawiki.user-blocks-change' );
		$eventFactory = $eventBus->getFactory();
		$event = $eventFactory->createUserBlockChangeEvent(
			$stream, $user, $block, $previousBlock );

		DeferredUpdates::addCallableUpdate(
			static function () use ( $eventBus, $event ) {
				$eventBus->send( [ $event ] );
			}
		);
	}

	/**
	 * Sends page-properties-change and page-links-change events
	 *
	 * Emits two events separately: one when the page properties change, and
	 * the other when links are added to or removed from the page.
	 *
	 * @see https://www.mediawiki.org/wiki/Manual:Hooks/LinksUpdateComplete
	 *
	 * @param LinksUpdate $linksUpdate the update object
	 */
	public static function onLinksUpdateComplete(
		LinksUpdate $linksUpdate
	) {
		$addedProps = $linksUpdate->getAddedProperties();
		$removedProps = $linksUpdate->getRemovedProperties();
		$arePropsEmpty = empty( $removedProps ) && empty( $addedProps );

		$addedLinks = $linksUpdate->getPageReferenceArray( 'pagelinks', LinksTable::INSERTED );
		$addedExternalLinks = $linksUpdate->getAddedExternalLinks();
		$removedLinks = $linksUpdate->getPageReferenceArray( 'pagelinks', LinksTable::DELETED );
		$removedExternalLinks = $linksUpdate->getRemovedExternalLinks();
		$areLinksEmpty = empty( $removedLinks ) && empty( $addedLinks )
			&& empty( $removedExternalLinks ) && empty( $addedExternalLinks );

		if ( $arePropsEmpty && $areLinksEmpty ) {
			return;
		}

		$title = $linksUpdate->getTitle();
		$user = $linksUpdate->getTriggeringUser();

		// Use triggering revision's rev_id if it is set.
		// If the LinksUpdate didn't have a triggering revision
		// (probably because it was triggered by sysadmin maintenance).
		// Use the page's latest revision.
		$revRecord = $linksUpdate->getRevisionRecord();
		if ( $revRecord ) {
			$revId = $revRecord->getId();
		} else {
			$revId = $title->getLatestRevID();
		}
		$pageId = $linksUpdate->getPageId();

		if ( !$arePropsEmpty ) {
			$stream = 'mediawiki.page-properties-change';
			$eventBus = EventBus::getInstanceForStream( $stream );
			$eventFactory = $eventBus->getFactory();
			$propEvent = $eventFactory->createPagePropertiesChangeEvent(
				$stream,
				$title,
				$addedProps,
				$removedProps,
				$user,
				$revId,
				$pageId
			);

			DeferredUpdates::addCallableUpdate(
				static function () use ( $eventBus, $propEvent ) {
					$eventBus->send( [ $propEvent ] );
				}
			);
		}

		if ( !$areLinksEmpty ) {
			$stream = 'mediawiki.page-properties-change';
			$eventBus = EventBus::getInstanceForStream( $stream );
			$eventFactory = $eventBus->getFactory();
			$linkEvent = $eventFactory->createPageLinksChangeEvent(
				'mediawiki.page-links-change',
				$title,
				$addedLinks,
				$addedExternalLinks,
				$removedLinks,
				$removedExternalLinks,
				$user,
				$revId,
				$pageId
			);

			DeferredUpdates::addCallableUpdate(
				static function () use ( $eventBus, $linkEvent ) {
					$eventBus->send( [ $linkEvent ] );
				}
			);
		}
	}

	/**
	 * Sends a page-restrictions-change event
	 *
	 * @param WikiPage $wikiPage the article which restrictions were changed
	 * @param User $user the user who have changed the article
	 * @param string[] $protect set of new restrictions details
	 * @param string $reason the reason for page protection
	 */
	public static function onArticleProtectComplete(
		WikiPage $wikiPage,
		User $user,
		array $protect,
		$reason
	) {
		$stream = 'mediawiki.page-restrictions-change';
		$eventBus = EventBus::getInstanceForStream( $stream );
		$eventFactory = $eventBus->getFactory();

		$event = $eventFactory->createPageRestrictionsChangeEvent(
			$stream,
			$user,
			$wikiPage->getTitle(),
			$wikiPage->getId(),
			$wikiPage->getRevisionRecord(),
			$wikiPage->isRedirect(),
			$reason,
			$protect
		);

		DeferredUpdates::addCallableUpdate(
			static function () use ( $eventBus, $event ) {
				$eventBus->send( [ $event ] );
			}
		);
	}

	/** Called after tags have been updated with the ChangeTags::updateTags function.
	 *
	 * @see https://www.mediawiki.org/wiki/Manual:Hooks/ChangeTagsAfterUpdateTags
	 *
	 * @param array $addedTags tags effectively added in the update
	 * @param array $removedTags tags effectively removed in the update
	 * @param array $prevTags tags that were present prior to the update
	 * @param int|null $rc_id recentchanges table id
	 * @param int|null $rev_id revision table id
	 * @param int|null $log_id logging table id
	 * @param string|null $params tag params
	 * @param RecentChange|null $rc RecentChange being tagged when the tagging accompanies
	 * the action, or null
	 * @param User|null $user User who performed the tagging when the tagging is subsequent
	 * to the action, or null
	 */
	public static function onChangeTagsAfterUpdateTags(
		array $addedTags,
		array $removedTags,
		array $prevTags,
		$rc_id,
		$rev_id,
		$log_id,
		$params,
		?RecentChange $rc,
		?User $user
	) {
		if ( $rev_id === null ) {
			// We're only interested for revision (edits) tags for now.
			return;
		}

		$revisionRecord = self::getRevisionLookup()->getRevisionById( $rev_id );
		if ( $revisionRecord === null ) {
			// Revision might already have been deleted, so we're not interested in tagging those.
			return;
		}

		$stream = 'mediawiki.revision-tags-change';
		$eventBus = EventBus::getInstanceForStream( $stream );
		$eventBusFactory = $eventBus->getFactory();
		$eventBusFactory->setCommentFormatter( MediaWikiServices::getInstance()->getCommentFormatter() );
		$event = $eventBusFactory->createRevisionTagsChangeEvent(
			$stream,
			$revisionRecord,
			$prevTags,
			$addedTags,
			$removedTags,
			$user
		);

		DeferredUpdates::addCallableUpdate(
			static function () use ( $eventBus, $event ) {
				$eventBus->send( [ $event ] );
			}
		);
	}

	/**
	 * Handle CentralNoticeCampaignChange hook. Send an event corresponding to the type
	 * of campaign change made (create, change or delete).
	 *
	 * This method is only expected to be called if CentralNotice is installed.
	 *
	 * @see https://www.mediawiki.org/wiki/Extension:CentralNotice/CentralNoticeCampaignChange
	 *
	 * @param string $changeType Type of change performed. Can be 'created', 'modified',
	 *   or 'removed'.
	 * @param string $time The time of the change. This is the same time that will be
	 *   recorded for the change in the cn_notice_log table.
	 * @param string $campaignName Name of the campaign created, modified or removed.
	 * @param User $user The user who performed the change.
	 * @param array|null $beginSettings Campaign settings before the change, if applicable.
	 *   These will include start, end, enabled, archived and banners. If not applicable,
	 *   this parameter will be null.
	 * @param array|null $endSettings Campaign settings after the change, if applicable.
	 *   These will include start, end, enabled, archived and banners. If not applicable,
	 *   this parameter will be null.
	 * @param string $summary Change summary provided by the user, or empty string if none
	 *   was provided.
	 */
	public static function onCentralNoticeCampaignChange(
		$changeType,
		$time,
		$campaignName,
		User $user,
		?array $beginSettings,
		?array $endSettings,
		$summary
	) {
		// Since we're running this hook, we'll assume that CentralNotice is installed.
		$campaignUrl = Campaign::getCanonicalURL( $campaignName );

		switch ( $changeType ) {
			case 'created':
				if ( !$endSettings ) {
					return;
				}

				$stream = 'mediawiki.centralnotice.campaign-create';
				$eventBus = EventBus::getInstanceForStream( $stream );
				$eventFactory = $eventBus->getFactory();
				$event = $eventFactory->createCentralNoticeCampaignCreateEvent(
					$stream,
					$campaignName,
					$user,
					$endSettings,
					$summary,
					$campaignUrl
				);
				break;

			case 'modified':
				if ( !$endSettings ) {
					return;
				}

				$stream = 'mediawiki.centralnotice.campaign-change';
				$eventBus = EventBus::getInstanceForStream( $stream );
				$eventFactory = $eventBus->getFactory();
				$event = $eventFactory->createCentralNoticeCampaignChangeEvent(
					$stream,
					$campaignName,
					$user,
					$endSettings,
					$beginSettings ?: [],
					$summary,
					$campaignUrl
				);
				break;

			case 'removed':
				$stream = 'mediawiki.centralnotice.campaign-delete';
				$eventBus = EventBus::getInstanceForStream( $stream );
				$eventFactory = $eventBus->getFactory();
				$event = $eventFactory->createCentralNoticeCampaignDeleteEvent(
					$stream,
					$campaignName,
					$user,
					$beginSettings ?: [],
					$summary,
					$campaignUrl
				);
				break;

			default:
				throw new UnexpectedValueException(
					'Bad CentralNotice change type: ' . $changeType );
		}

		DeferredUpdates::addCallableUpdate(
			static function () use ( $eventBus, $event ) {
				$eventBus->send( [ $event ] );
			}
		);
	}

}
